# .github/workflows/functions-gcp.yml
permissions:
  contents: read

on:
  workflow_call:


jobs:
  functions:
    name: Build code
    uses: ./.github/workflows/build-code.yml
    secrets: inherit

#  gcp-terraform:
#    name: GCP
#    uses: ./.github/workflows/gcp-arquitecture.yml
#    secrets: inherit
#    needs: [functions]
